# Generated by Django 4.1.5 on 2023-01-12 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='receptes.category')),
            ],
        ),
        migrations.CreateModel(
            name='Ingridient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('measure', models.CharField(choices=[('ml', 'Ml'), ('g', 'G'), ('gab', 'Gab')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recepie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('category', models.ManyToManyField(to='receptes.category')),
                ('recepie_ingridient', models.ManyToManyField(through='receptes.Ingridient', to='receptes.product')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('recepie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptes.recepie')),
            ],
        ),
        migrations.AddField(
            model_name='ingridient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptes.product'),
        ),
        migrations.AddField(
            model_name='ingridient',
            name='recepie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receptes.recepie'),
        ),
    ]
